### PR TITLE
Add integration tests 

### PR DESCRIPTION
**Pull request by KiKoS0**
Includes tests for most what the SDK supports at this time:
- Sleep
- Step-less functions
- Multi steps functions
- waitForEvent
- sendEvent

I'm not too sure if we should split the test cases into different classes or not. I think it's usually a good idea to always have smaller test files but the boilerplate overhead of each test class in Java is too much. Let me know what you think.

### CODE REVIEW

**Comment by darwin67** [comment]
what's the boilerplate overhead? I saw the TestHelper.java file and it looks like only a couple of import statements, which seems pretty small.

**Review by darwin67 — APPROVED** [review]
we can merge this for now, and discuss the ergonomics of defining Inngest functions in Java in a separate thread.

**Comment by KiKoS0** [comment]
@darwin67 oh just the annotations and `autowired` stuff but honestly i don't think it's that bad. I'll split them before merging because i don't like that everything is in one file.

**Review by albertchae — APPROVED** [review]
renames look good

**Pull request merged**
